# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Oct 18 16:23:01 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 595)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblCANBUS = QtGui.QLabel(self.centralwidget)
        self.lblCANBUS.setGeometry(QtCore.QRect(120, 0, 51, 16))
        self.lblCANBUS.setObjectName("lblCANBUS")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 460, 821, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lblTime = QtGui.QLabel(self.centralwidget)
        self.lblTime.setEnabled(False)
        self.lblTime.setGeometry(QtCore.QRect(290, 519, 71, 31))
        self.lblTime.setObjectName("lblTime")
        self.txtCANBUS = QtGui.QTextEdit(self.centralwidget)
        self.txtCANBUS.setGeometry(QtCore.QRect(0, 20, 371, 181))
        self.txtCANBUS.setReadOnly(True)
        self.txtCANBUS.setObjectName("txtCANBUS")
        self.lblMinTime = QtGui.QLabel(self.centralwidget)
        self.lblMinTime.setEnabled(False)
        self.lblMinTime.setGeometry(QtCore.QRect(50, 520, 16, 16))
        self.lblMinTime.setObjectName("lblMinTime")
        self.lblMaxTime = QtGui.QLabel(self.centralwidget)
        self.lblMaxTime.setEnabled(False)
        self.lblMaxTime.setGeometry(QtCore.QRect(690, 520, 51, 16))
        self.lblMaxTime.setObjectName("lblMaxTime")
        self.btnPlay = QtGui.QPushButton(self.centralwidget)
        self.btnPlay.setEnabled(False)
        self.btnPlay.setGeometry(QtCore.QRect(140, 519, 31, 31))
        self.btnPlay.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlay.setIcon(icon)
        self.btnPlay.setObjectName("btnPlay")
        self.btnStop = QtGui.QPushButton(self.centralwidget)
        self.btnStop.setEnabled(False)
        self.btnStop.setGeometry(QtCore.QRect(240, 519, 31, 31))
        self.btnStop.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon1)
        self.btnStop.setObjectName("btnStop")
        self.btnPause = QtGui.QPushButton(self.centralwidget)
        self.btnPause.setEnabled(False)
        self.btnPause.setGeometry(QtCore.QRect(190, 520, 31, 31))
        self.btnPause.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPause.setIcon(icon2)
        self.btnPause.setObjectName("btnPause")
        self.btnSxArrow = QtGui.QPushButton(self.centralwidget)
        self.btnSxArrow.setEnabled(False)
        self.btnSxArrow.setGeometry(QtCore.QRect(10, 490, 31, 31))
        self.btnSxArrow.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/sx_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSxArrow.setIcon(icon3)
        self.btnSxArrow.setObjectName("btnSxArrow")
        self.btnDxArrow = QtGui.QPushButton(self.centralwidget)
        self.btnDxArrow.setEnabled(False)
        self.btnDxArrow.setGeometry(QtCore.QRect(750, 490, 31, 31))
        self.btnDxArrow.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/dx_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDxArrow.setIcon(icon4)
        self.btnDxArrow.setObjectName("btnDxArrow")
        self.sldTime = QtGui.QSlider(self.centralwidget)
        self.sldTime.setGeometry(QtCore.QRect(50, 490, 691, 31))
        self.sldTime.setOrientation(QtCore.Qt.Horizontal)
        self.sldTime.setObjectName("sldTime")
        self.txtGpsData = QtGui.QTextEdit(self.centralwidget)
        self.txtGpsData.setGeometry(QtCore.QRect(0, 210, 371, 61))
        self.txtGpsData.setReadOnly(True)
        self.txtGpsData.setObjectName("txtGpsData")
        self.wdgGoogleMaps = QtGui.QWidget(self.centralwidget)
        self.wdgGoogleMaps.setGeometry(QtCore.QRect(0, 280, 371, 181))
        self.wdgGoogleMaps.setObjectName("wdgGoogleMaps")
        self.wdgVideo = QtGui.QWidget(self.centralwidget)
        self.wdgVideo.setGeometry(QtCore.QRect(380, 20, 391, 441))
        self.wdgVideo.setObjectName("wdgVideo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.infoMenu = QtGui.QMenu(self.menubar)
        self.infoMenu.setObjectName("infoMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_archive = QtGui.QAction(MainWindow)
        self.actionOpen_archive.setObjectName("actionOpen_archive")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen_archive)
        self.infoMenu.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.infoMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CANBUS Analyzer", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCANBUS.setText(QtGui.QApplication.translate("MainWindow", "CANBUS", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTime.setText(QtGui.QApplication.translate("MainWindow", "00:0000", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMinTime.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMaxTime.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.infoMenu.setTitle(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_archive.setText(QtGui.QApplication.translate("MainWindow", "Open archive", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))

